ver May8th
fixed bug in branch
supplemented prompts in branch

diff --git a/branch-tool/branch b/branch-tool/branch
--- a/branch-tool/branch
+++ b/branch-tool/branch
@@ -36,18 +36,20 @@ function r() {
 			--safe-links\
 			./ "$destpath"/"$branch_name"/
 		if [[ $(<branch-config/symlist) != "" ]]; then
-			ln -sf $(sed -e 's#^#'"$PWD"/'#g' branch-config/symlist) "$destpath"/"$branch_name"/
+			mapfile -t symfiles <(sed -e 's#^#'"$PWD"/'#g' branch-config/symlist)
+			ln -sf "${symfiles[@]}" "$destpath"/"$branch_name"/
 		fi
 	fi
 
-	echo "$branch_name"@"$destpath":"$autodelete"
-	cd "$destpath"/"$branch_name" || return
+	echo Branch Info: run at "$branch_name"@"$destpath":"$autodelete"
+	cd "$destpath"/"$branch_name" || echo "changing to $destpath/$branch_name error!" && return
 	shift 1
 	echo Command: "$@"
 	"$@"
 	returncode=$?
-	cd ~- || return
-	
+	cd ~- || echo "changing back to workdir error!" && return
+	echo Branch Info: run at "$branch_name"@"$destpath":"$autodelete"
+
 	if [[ $autodelete -ne 0 ]]; then
 		rm -rf "${destpath:?Empty Destpath}"/"$branch_name"
 	fi
